server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    basic:
      enabled: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000
    lettuce:
      pool:
        max-active: 100
        max-idle: 50
        min-idle: 10
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth_test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&cachePrepStmts=true&useServerPrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhaoshuai123
    hikari:
      pool-name: AuthServiceHikariCP
      auto-commit: true
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect